import {StyleSheet} from 'react-native';
import {Colors} from '../theme/colors';

export default StyleSheet.create({
  container: {flex: 1, backgroundColor: Colors.background},
  center: {flex: 1, justifyContent: 'center', alignItems: 'center'},
  header: {paddingTop: 54, paddingHorizontal: 16, paddingBottom: 8, backgroundColor: Colors.background},
  headerTitle: {color: '#fff', fontSize: 18, fontWeight: '900', letterSpacing: 1},
  yearRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  yearText: {color: Colors.yellow, fontSize: 22, fontWeight: '900', letterSpacing: 1},
  yearLabel: {color: Colors.textSecondary, fontSize: 11, fontWeight: '800', letterSpacing: 2},
  tabRow: {flexDirection: 'row', height: 44, backgroundColor: Colors.surface, borderBottomWidth: 1, borderBottomColor: Colors.outline},
  tab: {flex: 1, justifyContent: 'center', alignItems: 'center'},
  tabActive: {borderBottomWidth: 2, borderBottomColor: Colors.yellow},
  tabText: {color: Colors.textSecondary, fontSize: 10, fontWeight: '800', letterSpacing: 0.5},
  tabTextActive: {color: Colors.yellow},
  standingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.card,
    borderRadius: 10,
    padding: 14,
    marginBottom: 6,
  },
  pos: {color: '#fff', fontSize: 18, fontWeight: '900', width: 40, textAlign: 'center', marginRight: 8},
  driverName: {color: '#fff', fontSize: 14, fontWeight: '700'},
  teamName: {color: Colors.textSecondary, fontSize: 12},
  pointsBox: {alignItems: 'center', marginLeft: 8},
  points: {color: Colors.yellow, fontSize: 16, fontWeight: '900'},
  pointsLabel: {color: Colors.textSecondary, fontSize: 9, fontWeight: '700'},
  roundInfo: {color: Colors.textSecondary, fontSize: 12, fontWeight: '600', marginBottom: 12},
  roundCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.card,
    borderRadius: 10,
    padding: 14,
    marginBottom: 8,
  },
  roundLabel: {color: Colors.textSecondary, fontSize: 11, fontWeight: '700'},
  roundVenue: {color: '#fff', fontSize: 15, fontWeight: '700', marginTop: 2},
  roundDate: {color: Colors.textSecondary, fontSize: 12, marginTop: 2},
  tbc: {color: Colors.outline, fontSize: 11, fontWeight: '700'},
  emptyText: {color: Colors.textSecondary, fontSize: 14, textAlign: 'center', marginTop: 40},
  statCol: {width: 36, textAlign: 'center', color: Colors.textSecondary, fontSize: 13, fontWeight: '800'},
  statColHeader: {width: 36, textAlign: 'center', color: Colors.textSecondary, fontSize: 10, fontWeight: '700', letterSpacing: 0.5},
  scrollTopFab: {
    position: 'absolute',
    bottom: 20,
    right: 16,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.yellow,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  filterRow: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 4,
  },
  filterPill: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.outline,
  },
  filterPillActive: {
    backgroundColor: Colors.yellow,
    borderColor: Colors.yellow,
  },
  filterPillText: {
    color: Colors.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  filterPillTextActive: {
    color: Colors.navy,
  },
});
